name = "CloudSecurity"
version = "2.0"
description = "An open source"
license = "Apache-2.0"
repository = "https://github.com/RodgerZhu/Cloud_Security"
documentation = "https://cloudsecur.readthedocs.io/en/branch1.0/"
