name: Docker Image CI

on:
  pull_request:
    branches: [ branch3 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        pwd
        ls
        cd ./tensorflow-serving-cluster//tensorflow-serving/docker/tf_serving
        docker build -f gramine_tf_serving.dockerfile . -t tf_serving:$(date +%s)
